// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Winter.Core;

#nullable disable

namespace Winter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221009130504_UsersPhone")]
    partial class UsersPhone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Winter.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 9, 16, 5, 4, 206, DateTimeKind.Local).AddTicks(6630),
                            Email = "tt1@tt.tt",
                            FirstName = "Tester",
                            LastName = "Testerov",
                            Phone = "12-12-12"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 9, 16, 5, 4, 206, DateTimeKind.Local).AddTicks(6680),
                            Email = "tt2@tt.tt",
                            FirstName = "Mike",
                            LastName = "Tyson",
                            Phone = "13-99-14"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 9, 16, 5, 4, 206, DateTimeKind.Local).AddTicks(6680),
                            Email = "tt3@tt.tt",
                            FirstName = "Red",
                            LastName = "Sky",
                            Phone = "33-33-32"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
