version: '3.1'
services:
  
  winter-app:
    build:
      context: ../../
      dockerfile: ./docker/local/Dockerfile
    ports:
      - "7091:7091"
      - "5233:5233"
    network_mode: host
    volumes:
      - ../../:/app
  
  winter-db:
    image: mysql:5.7
    container_name: winter-db
    restart: unless-stopped
    tty: true
    user: 1000:1000
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: winter
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdata:/var/lib/mysql

  myadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - winter-db
    environment:
      PMA_HOST: winter-db
    ports:
      - '8081:80'
