// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Winter.Core;

#nullable disable

namespace Winter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LibraryUser", b =>
                {
                    b.Property<int>("LibrariesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("LibrariesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("LibraryUser");

                    b.HasData(
                        new
                        {
                            LibrariesId = 1,
                            UsersId = 1
                        },
                        new
                        {
                            LibrariesId = 1,
                            UsersId = 2
                        },
                        new
                        {
                            LibrariesId = 2,
                            UsersId = 3
                        });
                });

            modelBuilder.Entity("Main.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jane Austen",
                            BookName = "Pride and Prejudice",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            BookName = "1984",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Author = "Hamlet",
                            BookName = "William Shakespeare",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Main.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Some street"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Work street"
                        });
                });

            modelBuilder.Entity("Main.Models.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("Main.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 17, 22, 5, 26, 274, DateTimeKind.Local).AddTicks(5980),
                            Email = "tt1@tt.tt",
                            FirstName = "Tester",
                            LastName = "Testerov",
                            Password = "123456",
                            Phone = "12-12-12",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 17, 22, 5, 26, 274, DateTimeKind.Local).AddTicks(6030),
                            Email = "tt2@tt.tt",
                            FirstName = "Mike",
                            LastName = "Tyson",
                            Password = "123456",
                            Phone = "13-99-14",
                            Role = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 17, 22, 5, 26, 274, DateTimeKind.Local).AddTicks(6030),
                            Email = "tt3@tt.tt",
                            FirstName = "Red",
                            LastName = "Sky",
                            Password = "123456",
                            Phone = "33-33-32",
                            Role = "Owner"
                        });
                });

            modelBuilder.Entity("LibraryUser", b =>
                {
                    b.HasOne("Main.Models.Library", null)
                        .WithMany()
                        .HasForeignKey("LibrariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Models.Book", b =>
                {
                    b.HasOne("Main.Models.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Main.Models.User", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
