version: '3.1'
services:
  
  winter-db:
    network_mode: host
    image: mysql:5.7
    container_name: winter-db
    restart: unless-stopped
    tty: true
    user: 1000:1000
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: winter
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdata:/var/lib/mysql

  myadmin:
    network_mode: host
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 127.0.0.1
#      PMA_ARBITRARY: 1
    ports:
      - '8081:80'
